### ISSUE TITLE
Bugi: e:n muuntaminen neperin luvuksi

### ISSUE THREAD

**Issue by HHuttu** [henrivain/Matikkaeditorinkaantaja#10]
Fysiikka 2 tila ei muunna e-kirjainta neperin luvuksi. Ei taida olla muuta käyttöä e-kirjaimelle esim. yksiköissä tai missään, joten voisi varmaan hyvin muuntaa. 

Ti-Nspire käyttää neperin luvusta unicode symbolia "" (U+F03F), joten voisi varmaan sitä hyödyntää.

**Comment by henrivain** [comment]
## Pitäisi löytyä jo
Neperin luku on asetuksen takana, jotta matikkatilassa muuttuja "e" ei muuttuisi neperin luvuksi oletuksena. Sama asetus muuttaa neperin luvun niin matikkatilassa kuin fysiikkatila 2:ssa.

```
Päänäyttö > Asetukset > lisäasetukset >Muuta erityismerkit
```

![image](https://github.com/henrivain/Matikkaeditorinkaantaja/assets/89461562/f18b656a-712b-4cb6-b89d-b83a4ea28781)
  
![image](https://github.com/henrivain/Matikkaeditorinkaantaja/assets/89461562/cfcf27b6-ea3c-437d-b669-62dc428c7cc8)

Näppäränä ti-nspire temppuna on hyvä tietää, että neperin luku voidaan kirjoittaa näppäimistöltä kirjainyhdistelmällä `@e`

Kannattaa tutustua hyvin etusivulla näkyvään README.md tiedostoon. Olen kerännyt siihen parhaiten toimintaa nopeuttavia asetuksia ja muita temppuja Matikkaedtironkääntäjään.
