### ISSUE TITLE
Always on top -ominaisuus

### ISSUE THREAD

**Issue by HHuttu** [henrivain/Matikkaeditorinkaantaja#9]
Olisiko mahdollista lisätä tuki "always on top" -moodille, jossa ikkuna pysyisi aina muiden päällä? Nopeuttaisi kääntämistä jonkin verran, jos kääntämisnappi olisi aina näkyvillä.

Muuten tämä on mahtavan kätsy ohjelma! Nopeuttaa tehtävien tekoa paljon ja harmi, että löysin vasta kolmannen vuoden lopussa. Kiitos että olet tehnyt tämmösen👍

**Comment by henrivain** [comment]
Nopealla vilkaisulla kyllä pitäisi olla mahdollinen. Tutkin asiaa ja pyrin lisäämään toiminnon mahdollisimman nopeasti.
-Henri

**Comment by henrivain** [comment]
## Saatavilla v3.2.4
Ominaisuus on nyt saatavilla uudessa päivityksessä v3.2.4. Jos sen kanssa tulee ongelmia, ilmoita, niin voi yrittää korjata ne. Voit tällöin avata tämän uudelleen aktiiviseksi.
Onnea ja menestystä tuleviin yo-kirjoituksiin, jos sinulla vielä niitä on edessä.
Suljen tämän pyynnön nyt täytettynä.
-Henri

**Comment by HHuttu** [comment]
Kiitos paljon!🙏 Ja on kyllä kokeita vielä edessä, tää tulee auttamaan paljon lukemisessa.
